/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "timer.h"
#include "switch.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern int count;

int main(void)
{
	int duty = 0;
    int cState = 0;
    int pState = 0;
    int cycle = 0;

    SystemInit();
    TimerInit();
    SwitchInit(SWITCH);

    while(1)
    {
    	while(exti0_flag == 0)		{		controlPWM(duty);		}

        cState = 1;
        if(cState == 1)
        {
        	if(cState != pState)
        	{
        		if(duty == 0)			{		cycle = 0;		}
        		else if(duty == 100)	{		cycle = 1;		}

        		if(cycle == 0)			{		count = count + 10;		pState = cState;		}
        		else if(cycle == 1)		{		count = count - 10;		pState = cState;		}
        	}
        	else if(cState == pState)	{		count = count;		}
        }
        pState = 0;
        duty = count;
        exti0_flag = 0;
    }
	return 0;
}













